version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: BelgoData_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: BelgoData_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules

  ai-service:
    build: ./ai-service
    container_name: BelgoData_ai
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./ai-service:/app

  frontend:
    build: ./frontend
    container_name: BelgoData_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo_data: